### ISSUE TITLE
Adding package to fedora official repos

### ISSUE THREAD

**Issue by pszypowicz** [taw00/riot-rpm#13]
Would you consider adding this build process for official fedora repositories, or maybe you are aware of any obstacles to do so (like licensing problems etc.)

https://fedoraproject.org/wiki/Package_Review_Process

Thanks!

**Comment by taw00** [comment]
I just haven't pursued it. I think there was a library issue in the past. I will investigate.

**Comment by pszypowicz** [comment]
Awesome, I think that riot client fully deserves to be in the official repo :)

Thanks for your work!

**Comment by taw00** [comment]
Riot depends on libffmpeg.so -- I believe this is what blocks it from inclusion. I will investigate further, but I think that will halt the process.

I spent a good chunk of time trying to yank that library from the application... and riot complains loudly if it is not there. :(

**Comment by Seeder101** [comment]
Hi. 
what about using rpmfusion instead ?

**Comment by taw00** [comment]
Also... The way electron (and nodejs) apps generally build is a major issue with including them into major upstream repos. I.e., during the build, a zillion dependencies are downloaded from the internet. To be included, all of those dependencies **have** to be included in the source rpm (ie. a closed build). It's a task I may take up sometime, but right now... not a priority.

**Comment by tlaurion** [comment]
meanwhile please merge #24

**Comment by vc7ee** [comment]
Meanwhile you broke the fedora repo

**Comment by jtagcat** [comment]
Hi,
what about making your own distro with it preinstalled?

**Comment by taw00** [comment]
Merged #24. My own distro? HA!

**Comment by taw00** [comment]
Note, the route Fedora (and Red Hat and a number of other distros) are taking with the whole "npm/electron nightmare of a build issue" is that they are not shipping those applications. If you want them, build them for flatpak or snap or get them from upstream. Even building for RPM Fusion is a problem.

There are library and licensing issues (when you have a thousand modules, you just can't track everything) and there are build process issues: mature build environments are required to be airgapped and all source packages self-contained to the airgapped build environment.

So, I hope that makes since. Riot (now Element) does exist in flathub: <https://flathub.org/apps/details/im.riot.Riot>
