### ISSUE TITLE
Support for drpm

### ISSUE THREAD

**Issue by jtagcat** [taw00/riot-rpm#27]
Please support deltarpm, 300MB updates are insane.

**Comment by taw00** [comment]
53 to 59MB (depending on your OS distribution). But unfortunately, I can't. Not without hosting my own repositories. It doesn't seem that the COPR repos do a createrepo_c --update --deltas. Probably for scalability reasons.

**Comment by jtagcat** [comment]
Any stats on traffic? Could maybe host it.

**Comment by taw00** [comment]
Oh. I could easily host it myself. But I build a pile of RPMs... and they all funnel through COPR. I like to keep it simple. And Riot is a desktop application. 50 to 60MB is not horrible.

Note: I did file an RFE on this topic with Red Hat (COPR) and they are not going to support the feature due to the explosion of storage space it would require.

**Comment by taw00** [comment]
Oh. I could easily host it myself. But I build a pile of RPMs... and they all funnel through COPR. I like to keep it simple. And Riot is a desktop application. 50 to 60MB is not horrible.

Note: I did file an RFE on this topic with Red Hat (COPR) and they are not going to support the feature due to the explosion of storage space it would require.
